function monthDate(monthsAgo, day = 12) {
  const date = new Date()
  date.setDate(1)
  date.setMonth(date.getMonth() - monthsAgo)
  date.setDate(day)
  return date.toISOString().slice(0, 10)
}

export const sample = {
  producers: [
    {
      id: 'p1',
      name: 'Antônio Ferreira',
      cpf: '',
      phone: '(88) 90000-0001',
      community: 'Comunidade Esperança',
      consentAt: monthDate(4),
      status: 'Ativo',
    },
    {
      id: 'p2',
      name: 'Maria das Dores',
      cpf: '',
      phone: '(88) 90000-0002',
      community: 'Comunidade São José',
      consentAt: monthDate(2),
      status: 'Ativo',
    },
    {
      id: 'p3',
      name: 'José Ribeiro',
      cpf: '',
      phone: '(88) 90000-0003',
      community: 'Comunidade Lagoa Nova',
      consentAt: '',
      status: 'Ativo',
    },
    {
      id: 'p4',
      name: 'Ana Oliveira',
      cpf: '',
      phone: '(88) 90000-0004',
      community: 'Comunidade Boa Vista',
      consentAt: monthDate(1),
      status: 'Ativo',
    },
  ],
  properties: [
    {
      id: 'pr1',
      producerId: 'p1',
      name: 'Sítio Boa Esperança',
      area: 5.2,
      location: 'Redenção, CE',
    },
    {
      id: 'pr2',
      producerId: 'p2',
      name: 'Sítio São José',
      area: 3.8,
      location: 'Redenção, CE',
    },
    {
      id: 'pr3',
      producerId: 'p3',
      name: 'Sítio Lagoa Nova',
      area: 7.1,
      location: 'Acarape, CE',
    },
    {
      id: 'pr4',
      producerId: 'p4',
      name: 'Sítio Boa Vista',
      area: 4.5,
      location: 'Redenção, CE',
    },
  ],
  cultures: [
    { id: 'c1', name: 'Tomate', cycle: 'Curto', unit: 'kg' },
    { id: 'c2', name: 'Mandioca', cycle: 'Longo', unit: 'kg' },
    { id: 'c3', name: 'Milho', cycle: 'Curto', unit: 'kg' },
    { id: 'c4', name: 'Banana', cycle: 'Longo', unit: 'kg' },
  ],
  plantings: [
    {
      id: 'pl1',
      producerId: 'p1',
      propertyId: 'pr1',
      cultureId: 'c1',
      area: 1.8,
      cycle: 'Curto',
      startedAt: monthDate(4),
      expectedAt: monthDate(-1),
      endedAt: '',
      status: 'Em andamento',
    },
    {
      id: 'pl2',
      producerId: 'p2',
      propertyId: 'pr2',
      cultureId: 'c2',
      area: 2.4,
      cycle: 'Longo',
      startedAt: monthDate(6),
      expectedAt: monthDate(-3),
      endedAt: '',
      status: 'Em andamento',
    },
    {
      id: 'pl3',
      producerId: 'p3',
      propertyId: 'pr3',
      cultureId: 'c3',
      area: 3.2,
      cycle: 'Curto',
      startedAt: monthDate(3),
      expectedAt: monthDate(-1),
      endedAt: '',
      status: 'Em andamento',
    },
    {
      id: 'pl4',
      producerId: 'p4',
      propertyId: 'pr4',
      cultureId: 'c4',
      area: 2.1,
      cycle: 'Longo',
      startedAt: monthDate(5),
      expectedAt: monthDate(-2),
      endedAt: '',
      status: 'Em andamento',
    },
  ],
  production: [
    {
      id: 'pd1',
      plantingId: 'pl1',
      amount: 1200,
      unit: 'kg',
      date: monthDate(0, 5),
    },
    {
      id: 'pd2',
      plantingId: 'pl2',
      amount: 2100,
      unit: 'kg',
      date: monthDate(1, 18),
    },
    {
      id: 'pd3',
      plantingId: 'pl3',
      amount: 1650,
      unit: 'kg',
      date: monthDate(0, 10),
    },
    {
      id: 'pd4',
      plantingId: 'pl4',
      amount: 850,
      unit: 'kg',
      date: monthDate(1, 8),
    },
  ],
  categories: [
    { id: 'cat1', name: 'Insumos', system: false },
    { id: 'cat2', name: 'Transporte', system: false },
    { id: 'cat3', name: 'Equipamentos', system: false },
    { id: 'cat4', name: 'Mão de obra', system: true },
  ],
  expenses: [
    {
      id: 'e1',
      producerId: 'p1',
      categoryId: 'cat1',
      description: 'Sementes e adubo',
      amount: 1250,
      date: monthDate(1),
      plantingIds: ['pl1'],
      allocations: [{ plantingId: 'pl1', percent: 100, amount: 1250 }],
    },
    {
      id: 'e2',
      producerId: 'p2',
      categoryId: 'cat2',
      description: 'Transporte da colheita',
      amount: 680,
      date: monthDate(0),
      plantingIds: ['pl2'],
      allocations: [{ plantingId: 'pl2', percent: 100, amount: 680 }],
    },
    {
      id: 'e3',
      producerId: 'p3',
      categoryId: 'cat1',
      description: 'Preparação do solo',
      amount: 920,
      date: monthDate(2),
      plantingIds: ['pl3'],
      allocations: [{ plantingId: 'pl3', percent: 100, amount: 920 }],
    },
  ],
  dailies: [
    {
      id: 'd1',
      plantingId: 'pl1',
      nature: 'Paga',
      days: 3,
      unitValue: 90,
      amount: 270,
      date: monthDate(0, 9),
    },
    {
      id: 'd2',
      plantingId: 'pl2',
      nature: 'Familiar',
      days: 2,
      unitValue: 90,
      amount: 180,
      date: monthDate(1, 10),
    },
  ],
  references: [{ id: 'ref1', value: 90, startsAt: monthDate(8) }],
  clients: [
    {
      id: 'cl1',
      name: 'Feira da comunidade',
      channel: 'Feira',
      salesCount: 2,
      totalPurchased: 5254,
    },
    {
      id: 'cl2',
      name: 'Mercado Central',
      channel: 'Comércio local',
      salesCount: 1,
      totalPurchased: 3010,
    },
  ],
  sales: [
    {
      id: 's1',
      producerId: 'p1',
      clientId: 'cl1',
      date: monthDate(0, 14),
      items: [{ plantingId: 'pl1', amount: 340, unit: 'kg', unitPrice: 7.5 }],
      total: 2550,
    },
    {
      id: 's2',
      producerId: 'p2',
      clientId: 'cl2',
      date: monthDate(1, 21),
      items: [{ plantingId: 'pl2', amount: 700, unit: 'kg', unitPrice: 4.3 }],
      total: 3010,
    },
    {
      id: 's3',
      producerId: 'p3',
      clientId: 'cl1',
      date: monthDate(0, 16),
      items: [{ plantingId: 'pl3', amount: 520, unit: 'kg', unitPrice: 5.2 }],
      total: 2704,
    },
  ],
  results: [
    {
      plantingId: 'pl1',
      produced: 1200,
      sold: 340,
      revenue: 2550,
      expense: 1250,
      paidLabor: 270,
      familyLabor: 0,
      cost: 1520,
      result: 1030,
    },
    {
      plantingId: 'pl2',
      produced: 2100,
      sold: 700,
      revenue: 3010,
      expense: 680,
      paidLabor: 0,
      familyLabor: 180,
      cost: 680,
      result: 2330,
    },
    {
      plantingId: 'pl3',
      produced: 1650,
      sold: 520,
      revenue: 2704,
      expense: 920,
      paidLabor: 0,
      familyLabor: 0,
      cost: 920,
      result: 1784,
    },
    {
      plantingId: 'pl4',
      produced: 850,
      sold: 0,
      revenue: 0,
      expense: 0,
      paidLabor: 0,
      familyLabor: 0,
      cost: 0,
      result: 0,
    },
  ],
  stock: [
    { plantingId: 'pl1', produced: 1200, sold: 340, available: 860 },
    { plantingId: 'pl2', produced: 2100, sold: 700, available: 1400 },
    { plantingId: 'pl3', produced: 1650, sold: 520, available: 1130 },
    { plantingId: 'pl4', produced: 850, sold: 0, available: 850 },
  ],
  dashboard: {
    producerCount: 4,
    activePlantingCount: 4,
    revenue: 8264,
    result: 5144,
    bars: [
      { key: 'm5', label: 'M-5', revenue: 0, expense: 0 },
      { key: 'm4', label: 'M-4', revenue: 0, expense: 0 },
      { key: 'm3', label: 'M-3', revenue: 0, expense: 920 },
      { key: 'm2', label: 'M-2', revenue: 0, expense: 0 },
      { key: 'm1', label: 'M-1', revenue: 3010, expense: 1250 },
      { key: 'm0', label: 'Atual', revenue: 5254, expense: 950 },
    ],
    cultures: [
      { id: 'c2', name: 'Mandioca', value: 3010, width: 82 },
      { id: 'c3', name: 'Milho', value: 2704, width: 74 },
      { id: 'c1', name: 'Tomate', value: 2550, width: 69 },
    ],
  },
  resultSummary: { revenue: 8264, cost: 3120, result: 5144 },
  reports: [
    {
      id: 'r1',
      producerId: 'p1',
      from: monthDate(4),
      to: monthDate(0),
      issuedAt: monthDate(0),
      snapshot: {
        producer: {
          id: 'p1',
          name: 'Antônio Ferreira',
          community: 'Comunidade Esperança',
          consentAt: monthDate(4),
        },
        properties: [{ id: 'pr1', name: 'Sítio Boa Esperança' }],
        summary: {
          produced: 1200,
          sold: 340,
          revenue: 2550,
          cost: 1520,
          profit: 1030,
          familyLabor: 0,
        },
        plantings: [
          {
            id: 'pl1',
            culture: 'Tomate',
            area: 1.8,
            result: {
              produced: 1200,
              sold: 340,
              revenue: 2550,
              expense: 1250,
              paidLabor: 270,
            },
          },
        ],
      },
    },
  ],
  users: [
    {
      id: 'u1',
      nome: 'Administrador AgroGestão',
      login: 'admin',
      perfil: 'ADMIN',
      ativo: true,
    },
    {
      id: 'u2',
      nome: 'Roberto Nascimento Xavier',
      login: 'operador',
      perfil: 'OPERADOR',
      ativo: true,
    },
    {
      id: 'u3',
      nome: 'Equipe de consulta',
      login: 'consulta',
      perfil: 'CONSULTA',
      ativo: true,
    },
  ],
}
